options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Unit tests
- name: 'python:3.12'
  id: 'Run Unit Tests'
  dir: 'services/src_to_land_gcs'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install -r requirements.txt
      pytest -v

# Build SHA image
- name: 'gcr.io/cloud-builders/docker'
  dir: '${_SOURCE_DIR}'
  args:
    - build
    - -t
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
    - .

# Tag latest
- name: 'gcr.io/cloud-builders/docker'
  args:
    - tag
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:latest'

# Push SHA
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'

# Push latest
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:latest'

# Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: '${_SOURCE_DIR}'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - '${_SERVICE_NAME}'
    - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
    - '--region=${_REGION}'
    - '--service-account=${_SERVICE_ACCOUNT}'
    - '--env-vars-file=deploy.env'
